// Configures PAD settings for pins.

#include "pad_control.h"

#include "clock_control.h"
#include "io_mapping.h"
#include <pad_config.h>

#define PAD_CFG_GPIO (0b00u)
#define PAD_CFG_SERIAL (0b01u)
#define PAD_CFG_SERIAL_TIMER (0b10u)
#define PAD_CFG_ANALOG (0b11u)

#define PAD_DS_2mA (0b00u)
#define PAD_DS_4mA (0b01u)
#define PAD_DS_8mA (0b10u)

#define PAD_PUPD_NR (0b00u)
#define PAD_PUPD_PU (0b01u)
#define PAD_PUPD_PD (0b10u)

#define SET_PAD_BITS(REG, PIN, VALUE)        \
    REG = (REG & ~PAD_CONFIG_PIN_M(PIN)) | (PAD_CONFIG_PIN(PIN, VALUE))


void PAD_init(void) {
    Clock_enable_PAD_Config();
}

void PAD_UART0_settings(void) {
    SET_PAD_BITS(UART_0_PAD_CFG_REG, UART_0_RX_PIN, PAD_CFG_SERIAL);
    SET_PAD_BITS(UART_0_PAD_DS_REG, UART_0_RX_PIN, PAD_DS_2mA);
    SET_PAD_BITS(UART_0_PAD_PUPD_REG, UART_0_RX_PIN, PAD_PUPD_NR);
    
    SET_PAD_BITS(UART_0_PAD_CFG_REG, UART_0_TX_PIN, PAD_CFG_SERIAL);
    SET_PAD_BITS(UART_0_PAD_DS_REG, UART_0_TX_PIN, PAD_DS_2mA);
    SET_PAD_BITS(UART_0_PAD_PUPD_REG, UART_0_TX_PIN, PAD_PUPD_NR);
}

void PAD_I2C1_settings(void) {
    SET_PAD_BITS(I2C_1_PAD_CFG_REG, I2C_1_SCL_PIN, PAD_CFG_SERIAL);
    SET_PAD_BITS(I2C_1_PAD_DS_REG, I2C_1_SCL_PIN, PAD_DS_2mA);
    SET_PAD_BITS(I2C_1_PAD_PUPD_REG, I2C_1_SCL_PIN, PAD_PUPD_PU);

    SET_PAD_BITS(I2C_1_PAD_CFG_REG, I2C_1_SDA_PIN, PAD_CFG_SERIAL);
    SET_PAD_BITS(I2C_1_PAD_DS_REG, I2C_1_SDA_PIN, PAD_DS_2mA);
    SET_PAD_BITS(I2C_1_PAD_PUPD_REG, I2C_1_SDA_PIN, PAD_PUPD_PU);
}

void PAD_BUZZER_settings(void) {
    SET_PAD_BITS(BUZZER_PAD_CFG_REG, BUZZER_PIN, PAD_CFG_GPIO);
    SET_PAD_BITS(BUZZER_PAD_DS_REG, BUZZER_PIN, PAD_DS_2mA);
    SET_PAD_BITS(BUZZER_PAD_PUPD_REG, BUZZER_PIN, PAD_PUPD_NR);
}

void PAD_DHT11_settings(void) {
    SET_PAD_BITS(DHT11_PAD_CFG_REG, DHT11_PIN, PAD_CFG_GPIO);
    SET_PAD_BITS(DHT11_PAD_DS_REG, DHT11_PIN, PAD_DS_2mA);
    SET_PAD_BITS(DHT11_PAD_PUPD_REG, DHT11_PIN, PAD_PUPD_NR);
}