#pragma once

#define APP_COMMANDS_NONE_S         (0u)
#define APP_COMMAND_SETTIME_S       (1u)
#define APP_COMMAND_SETDATE_S       (2u)
#define APP_COMMAND_DISPLAYON_S     (3u)
#define APP_COMMAND_DISPLAYOFF_S    (4u)
#define APP_COMMAND_SETALARMTIME_S  (5u)
#define APP_COMMAND_SHOWALARMTIME_S (6u)
#define APP_COMMAND_ALARMON_S       (7u)
#define APP_COMMAND_ALARMOFF_S      (8u)
#define APP_COMMAND_SHOWTH_S        (9u)


#define APP_COMMANDS_NONE_M         (1u << APP_COMMANDS_NONE_S)
#define APP_COMMAND_SETTIME_M       (1u << APP_COMMAND_SETTIME_S)
#define APP_COMMAND_SETDATE_M       (1u << APP_COMMAND_SETDATE_S)
#define APP_COMMAND_DISPLAYON_M     (1u << APP_COMMAND_DISPLAYON_S)
#define APP_COMMAND_DISPLAYOFF_M    (1u << APP_COMMAND_DISPLAYOFF_S)
#define APP_COMMAND_SETALARMTIME_M  (1u << APP_COMMAND_SETALARMTIME_S)
#define APP_COMMAND_SHOWALARMTIME_M (1u << APP_COMMAND_SHOWALARMTIME_S)
#define APP_COMMAND_ALARMON_M       (1u << APP_COMMAND_ALARMON_S)
#define APP_COMMAND_ALARMOFF_M      (1u << APP_COMMAND_ALARMOFF_S)
#define APP_COMMAND_SHOWTH_M        (1u << APP_COMMAND_SHOWTH_S)