#pragma once

#define APP_EVENT_NONE_S                            (0u)

#define APP_EVENT_TIMER32_1_IS_OVERFLOW_S           (1u)

#define APP_EVENT_LCD_DRIVER_CLEAR_ERROR_S          (2u)
#define APP_EVENT_LCD_DRIVER_SETCURSOR_ERROR_S      (3u)
#define APP_EVENT_LCD_DRIVER_WRITE_ERROR_S          (4u)
#define APP_EVENT_LCD_DRIVER_DISPLAY_ERROR_S        (5u)

#define APP_EVENT_RTC_DRIVER_SETTIME_ERROR_S        (6u)
#define APP_EVENT_RTC_DRIVER_SETDATE_ERROR_S        (7u)
#define APP_EVENT_RTC_DRIVER_SETALARM_ERROR_S       (8u)
#define APP_EVENT_RTC_DRIVER_GETTIME_ERROR_S        (9u)
#define APP_EVENT_RTC_DRIVER_GETDATE_ERROR_S        (10u)
#define APP_EVENT_RTC_DRIVER_GETALARM_ERROR_S       (11u)

#define APP_EVENT_UART_DRIVER_OVERFLOW_ERROR_S      (12u)
#define APP_EVENT_UART_DRIVER_GETCOMMAND_ERROR_S    (13u)
#define APP_EVENT_UART_DRIVER_EMPTYCOMMAND_ERROR_S  (14u)
#define APP_EVENT_UART_DRIVER_INVALIDARG_ERROR_S    (15u)
#define APP_EVENT_UART_DRIVER_UNKCOMMAND_ERROR_S    (16u)

#define APP_EVENT_RTC_IS_ALARM_S                    (17u)

#define APP_EVENT_DHT11_DRIVER_INVALIDARG_ERROR_S   (18u)
#define APP_EVENT_DHT11_DRIVER_READ_ERROR_S         (19u)


#define APP_EVENT_NONE_M                            (1u << APP_EVENT_NONE_S)
    
#define APP_EVENT_TIMER32_1_IS_OVERFLOW_M           (1u << APP_EVENT_TIMER32_1_IS_OVERFLOW_S)
    
#define APP_EVENT_LCD_DRIVER_CLEAR_ERROR_M          (1u << APP_EVENT_LCD_DRIVER_CLEAR_ERROR_S)
#define APP_EVENT_LCD_DRIVER_SETCURSOR_ERROR_M      (1u << APP_EVENT_LCD_DRIVER_SETCURSOR_ERROR_S)
#define APP_EVENT_LCD_DRIVER_WRITE_ERROR_M          (1u << APP_EVENT_LCD_DRIVER_WRITE_ERROR_S)
#define APP_EVENT_LCD_DRIVER_DISPLAY_ERROR_M        (1u << APP_EVENT_LCD_DRIVER_DISPLAY_ERROR_S)
    
#define APP_EVENT_RTC_DRIVER_SETTIME_ERROR_M        (1u << APP_EVENT_RTC_DRIVER_SETTIME_ERROR_S)
#define APP_EVENT_RTC_DRIVER_SETDATE_ERROR_M        (1u << APP_EVENT_RTC_DRIVER_SETDATE_ERROR_S)
#define APP_EVENT_RTC_DRIVER_SETALARM_ERROR_M       (1u << APP_EVENT_RTC_DRIVER_SETALARM_ERROR_S)
#define APP_EVENT_RTC_DRIVER_GETTIME_ERROR_M        (1u << APP_EVENT_RTC_DRIVER_GETTIME_ERROR_S)
#define APP_EVENT_RTC_DRIVER_GETDATE_ERROR_M        (1u << APP_EVENT_RTC_DRIVER_GETDATE_ERROR_S)
#define APP_EVENT_RTC_DRIVER_GETALARM_ERROR_M       (1u << APP_EVENT_RTC_DRIVER_GETALARM_ERROR_S)

#define APP_EVENT_UART_DRIVER_OVERFLOW_ERROR_M      (1u << APP_EVENT_UART_DRIVER_OVERFLOW_ERROR_S)
#define APP_EVENT_UART_DRIVER_GETCOMMAND_ERROR_M    (1u << APP_EVENT_UART_DRIVER_GETCOMMAND_ERROR_S)
#define APP_EVENT_UART_DRIVER_EMPTYCOMMAND_ERROR_M  (1u << APP_EVENT_UART_DRIVER_EMPTYCOMMAND_ERROR_S)
#define APP_EVENT_UART_DRIVER_INVALIDARG_ERROR_M    (1u << APP_EVENT_UART_DRIVER_INVALIDARG_ERROR_S)
#define APP_EVENT_UART_DRIVER_UNKCOMMAND_ERROR_M    (1u << APP_EVENT_UART_DRIVER_UNKCOMMAND_ERROR_S)

#define APP_EVENT_RTC_IS_ALARM_M                    (1u << APP_EVENT_RTC_IS_ALARM_S)

#define APP_EVENT_DHT11_DRIVER_INVALIDARG_ERROR_M   (1u << APP_EVENT_DHT11_DRIVER_INVALIDARG_ERROR_S)
#define APP_EVENT_DHT11_DRIVER_READ_ERROR_M         (1u << APP_EVENT_DHT11_DRIVER_READ_ERROR_S)  